version: "3"
services:
  web:
    build: ./eestec_web
    container_name: eestec-web
    ports:
      - "8080:3000"
    depends_on:
      - backend
    networks:
      default:

  backend:
    build: ./eestec-backend
    links:
      - "db"
    ports:
      - 5049:5049
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SECRET_KEY=hrhr*0ydacw0^4627=7383wo5a!dajgbr&fkp6!nsq98ius0pw
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES = 30
      - DATABASE_URL=postgresql+asyncpg://user:1234@db:5432/postgres
    command: ["python", "main.py"]
    networks:
      default:

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: user
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "user"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      default:

